version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/application
hooks:
  ApplicationStop:
     - location: stop_script.sh
       timeout: 180
       runas: root
  Install:
     - location: install_script.sh
       timeout: 180
       runas: root
  ApplicationStart:
     - location: start_script.sh
       timeout: 180
       runas: root
