version: 0.2

pharse:
  build:
    commands:
      - echo Build started on 'date'
      - mvn package
  post_build:
    commands:
      - echo Build completed on 'date'
artifacts:
  files: 
    - '**/*'
