steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
- name: "gcr.io/gcr.io/cloud-builders/gcloud"
  args:
  - "${_JAVA}"
  timeout: 500s
artifacts:
  objects:
    location: "gs://${_BUCKET}/"
    paths:
    - "${_CLASS}"
