steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
  timeout: 500s
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/myfirstproject/my-image', '.']
  timeout: 500s
  args: ['push', 'gcr.io/myfirstproject/my-image']
