steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
  timeout: 500s
- name: 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
  args:
    - '-Dsonar.host.url=http://sonarcloud.io/'
    - '-Dsonar.login=ddf62d9752ae13da20242484ff765379fb801fb4'
    - '-Dsonar.projectKey=petclinic'
    - '-Dsonar.organization=vicknesh22-github'
    - '-Dsonar.sources=.'
  args: ['build', '-t', 'gcr.io/elite-monolith-240704/my-image', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/elite-monolith-240704/my-image']

 

